[package]
name = "cosmic-application-template"
version = "0.1.0"
authors = ["Ashley Wulber <ashley@system76.com>"]
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
once_cell = "1.9"
relm4 = { git = "https://github.com/Relm4/Relm4", features = ["all"] }
tokio = { version = "1.20", features = ["rt", "macros", "time", "rt-multi-thread"] }
tracker = "0.1"
futures = "0.3.21"
libcosmic = { git = "https://github.com/pop-os/libcosmic", default-features = false }
xdg = "2.4.0"
# Application i18n
i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.4"
rust-embed = "6.3.0"
adw-user-colors-lib = { git = "https://github.com/pop-os/user-color-editor" }

[build-dependencies]
glib-build-tools = { git = "https://github.com/gtk-rs/gtk-rs-core" }
